import React from 'react';
import Card from 'react-bootstrap/Card';

import {
  BrowserRouter as Router,
  Link
} from "react-router-dom";

import generateDynaStripes from '../dynastripes.js';

class AboutComponent extends React.Component {

    render() {
      const svgString = encodeURIComponent(generateDynaStripes());
      const svgDataUri = `url("data:image/svg+xml,${svgString}")`;

      return (
        <div className="mainContent"  style={{background: svgDataUri}}>
          <Card id="mainCard">
            <Card.Title
            ><h1>More About <span className="dyna">DynaStripes</span></h1>
            </Card.Title> 
            <div className="deepContent">
              <h4 className="dyna">
                  Overview
              </h4>
              <Card.Text>
                  <p>
                  <span className="dyna">DynaStripes</span> is an NFT art project created by the colour-blind, colour-obsessed visual artist, <a className="externalLink volstrate" href="http://www.volstrate.com" target="_blank">volstrate</a>. <span className="dyna">DynaStripes</span> represents the on-chain, generative evolution of volstrate's earlier explorations into NFT art. <span className="dyna">DynaStripes</span> NFTs are both <b>generative</b>, in the sense that the artwork is created programatically via the use of an algorithm, and <b>on-chain</b>, meaning that the creation algorithm, user inputs, and the artwork itself are stored directly on the Ethereum blockchain in the <span className="dyna">DynaStripes</span> smart contract. 
                  </p>
                  <p>Minting refers to the process of immutably comitting an artwork to a blockchain. Nearly all NFT art projects issue newly minted artwork in one of two ways: </p>
                  <ol>
                    <li>Blindly and pseudorandomly allow end-users to mint artwork generated during the minting process, the user only knowing what they've bought after the work has been paid for and fully minted.</li> 
                    <li>The artist or their delegate create the artwork themselves in advance and then offer if for sale either directly, or via a minting process during which the artwork may be randomly selected, but not generated. </li>
                  </ol>
                  <p> This latter form is usually referred to as "<b>artist-directed</b>" generative art as the artist can tweak the generation algorithm and its parameters before the artwork's creation, discard poor quality work, and keep or offer sale the work that has some subjective quality. Conversely, <span className="dyna">DynaStripes</span> is the first generative, on-chain NFT art project that is "<b>user-directed</b>," allowing end-users themselves to have control over inputs involved in the minting process.
                  </p>
              </Card.Text>

              <h4 className="dyna">
                Artwork generation
              </h4>

              <Card.Text>
                <p>
                  <span className="dyna">DynaStripes</span> artwork is created using input values from the user and pseudorandom values generated from the smart contract. These user inputs are stored directly in the contract upon minting, while the pseudorandom values are used deterministically when generating the artwork's SVG. The artwork is generated by the smart contract populating an SVG template with these values. This is done via a gas-free view operaton when the SVG is requested from the contract. SVG is a W3 open standard for scalable vector graphics, and is supported by nearly all web browsers.
                </p>
              </Card.Text>

              <h4 className="dyna">
                Influences
              </h4>

              <Card.Text>
                <p>
                  The <span className="dyna">DynaStripes</span> project has been heavily influenced by existing on-chain, generative art projects like <a className="externalLink" href="https://www.larvalabs.com/autoglyphs" target="_blank">Autoglyphs</a>, <a className="externalLink" href="https://avastars.io/" target="_blank">Avastars</a>, and <a className="externalLink" href="https://www.artblocks.io/" target="_blank">ArtBlocks</a>, but the most compelling source of inspiration has proven to be Simon de la Rouviere's <a className="externalLink" href="https://neolastics.com/" target="_blank">Neolastics</a> and also his writings, particularly this <a className="externalLink" href='https://blog.simondlr.com/posts/flavours-of-on-chain-svg-nfts-on-ethereum' target="_blank">fascinating piece.</a>
                </p>
              </Card.Text>
            </div>

            <a className="externalLink" href="mail:volstrate@gmail.com">Contact</a>
          </Card>
        </div>

      );
    }
  }

export default AboutComponent;