import React from 'react';
import Card from 'react-bootstrap/Card';

import {
  BrowserRouter as Router,
  Link
} from "react-router-dom";

import generateDynaStripes from '../dynastripes.js';

class AboutComponent extends React.Component {

    render() {
      const svgString = encodeURIComponent(generateDynaStripes());
      const svgDataUri = `url("data:image/svg+xml,${svgString}")`;

      return (
        <div className="mainContent"  style={{background: svgDataUri}}>
          <Card id="mainCard">
            <Card.Title
            ><h1>More About <span className="dyna">DynaStripes</span></h1>
            </Card.Title>


            <Card.Text>
                <p>
                <span className="dyna">DynaStripes</span> is an NFT art project created by the colour-blind, colour-obsessed visual artist, <a className="externalLink volstrate" href="http://www.volstrate.com" target="_blank">volstrate</a>. <span className="dyna">DynaStripes</span> represents the on-chain, generative evolution of volstrate's earlier explorations into NFT art.
                </p>
            </Card.Text>

            <Card.Title>
              Artwork generation
            </Card.Title>

            <Card.Text>
              <p>
                <span className="dyna">DynaStripes</span> artwork is created using input values from the user and pseudorandom values generated from the smart contract. These user inputs are stored directly in the contract upon minting, while the pseudorandom values are used deterministically when generating the artwork's SVG. The artwork is generated by the smart contract by populating an SVG template with these values. This is done as a view, gas-free operaton when the svg is requested from the contract. 
              </p>
            </Card.Text>

            <Card.Title>
              Influences
            </Card.Title>

            <Card.Text>
              <p>
                The <span className="dyna">DynaStripes</span> project has been heavily influenced by existing on-chain, generative art projects like <a className="externalLink" href="https://www.larvalabs.com/autoglyphs" target="_blank">Autoglyphs</a>, <a className="externalLink" href="https://avastars.io/" target="_blank">Avastars</a>, and <a className="externalLink" href="https://www.artblocks.io/" target="_blank">ArtBlocks</a>, but the most compelling source of inspiration has proven to be Simon de la Rouviere's <a className="externalLink" href="https://neolastics.com/" target="_blank">Neolastics</a> and also his writings, particularly this <a className="externalLink" href='https://blog.simondlr.com/posts/flavours-of-on-chain-svg-nfts-on-ethereum' target="_blank">fascinating piece.</a>
              </p>
            </Card.Text>

            <a href="mail:volstrate@gmail.com">Contact</a>
          </Card>
        </div>

      );
    }
  }

export default AboutComponent;